### ISSUE TITLE
FillNA limits for Interpolate, NOCB, LOCF

### ISSUE THREAD

**Issue by adinhobl** [invenia/Impute.jl#110]
Hi, 

In Pandas DataFrames, their methods for [interpolating](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html) and [fillna](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html) have a `limit` keyword, which essentially cuts the imputing routine short after a certain number of fills. 

This is useful if you want to forward fill timeseries data by a "reasonable" amount, but not necessarily to the next point. Is this implemented somewhere else, or would it be useful in this package? Or is there a trivial workaround I haven't thought of. I'm not averse to trying to implement it myself.

Thanks!

**Comment by rofinn** [comment]
Please take a look at #117 to confirm that it does what you'd like. `LOCF` and `NOCB` will fill up-to the limit, but `Interpolate` will only fill gaps <= limit.
