### ISSUE TITLE
Documentation failing to build

### ISSUE THREAD

**Issue by mattBrzezinski** [invenia/Impute.jl#120]
- https://github.com/invenia/Impute.jl/runs/3457597069?check_suite_focus=true

**Comment by morris25** [comment]
This still appears to be happening https://github.com/invenia/Impute.jl/runs/4390001626?check_suite_focus=true.
It looks like the doctests just need updating.

**Comment by rofinn** [comment]
I think https://github.com/invenia/Impute.jl/pull/126 fixes the issue.
