### ISSUE TITLE
Interpolation between two identical values

### ISSUE THREAD

**Issue by ErwanPiR** [invenia/Impute.jl#18]
Hi,

It seems that the implementation cannot deal with interpolation between two identical values...

For example, let's say you have an array like this :
`x = [1, 1, 1, 2, 2, 2, 3, missing, 3, 4, 4, 4]`
Obviously the result of the interpolation to replace the missing value should be 3 !

But using impute with :interp result in an error
`impute(x, :interp)`
`ERROR: ArgumentError: range step cannot be zero`

In fact in interp.jl, line 33 you do 
`values = Real(start_val):Real(incr):Real(stop_val)`
with cause the error due to identical values on the left and right side of the missing in the array.

Can you add an exception in this case ?

Thanks.

**Comment by rofinn** [comment]
Should be fixed on master. Thanks for raising the issue 👍 

```
julia> using Impute

julia> x = [1, 1, 1, 2, 2, 2, 3, missing, 3, 4, 4, 4]
12-element Array{Union{Missing, Int64},1}:
 1
 1
 1
 2
 2
 2
 3
  missing
 3
 4
 4
 4

julia> impute(x, :interp)
12-element Array{Union{Missing, Int64},1}:
 1
 1
 1
 2
 2
 2
 3
 3
 3
 4
 4
 4
```
