### ISSUE TITLE
`vardim` keyword should belong to `impute!` call

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/Impute.jl#32]
On `master`, I was recently burned by this:
```julia
# I know I only ever want to impute with the mean
method = Impute.Fill(; value=mean);

# do some initial data stuff here...
# notice after processing the data has observations in the columns

# let's impute the missings!
impute!(X, method; vardim=1)
julia> impute!(X, method; vardim=1)
ERROR: MethodError: no method matching impute!(::Array{Float64,2}, ::Fill{typeof(mean)}; vardim=1)
Closest candidates are:
  impute!(::AbstractArray{T,2} where T, ::Impute.Imputor) at /Users/nick/.julia/packages/Impute/OIgZp/src/imputors.jl:71 got unsupported keyword argument "vardim"
```
i.e. I want to specify my imputation method up front, but I don't know until call time how my data will be stored

But it turns out I need this
```julia
# know up front how data is stored
method = Impute.Fill(; value=mean, vardim=1);

# do inital data stuff and make the data the way round the `method` requires

# now impute
impute!(X, method)
```

Similar use case is: I want to allow users to specify _how_ to impute the data in the middle of some long data processing pipeline, _without_ requiring them to know the orientation the data happens to have at the time imputation is performed.

**Comment by rofinn** [comment]
The issue with this comes from the fact that our `Impute.<method>` functions need to both create the type using keywords and then call `impute!`. If we want to pass keywords to both then we'd need some way of figuring out which keywords should go to the type constructor and which should be passed to the `impute!` call. I suppose 1 option could be to use a default method that assumes keyword arguments to a type constructor match the field names and then pass the rest to the `impute!` method, but that seems hacky.

**Comment by nicoleepp** [comment]
Could have a kwarg for the keywords (as a Dict or namedtuple) that should go to the type contructor and pass the rest to the impute! method
