### ISSUE TITLE
How to pass a "chain" of imputors?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/Impute.jl#33]
Suppose I have code like 
```julia
struct Model
    theta
    imputor::Impute.Imputor
end

preprocess(m::Model, X) = impute(X, Model.imputor)
```
How would a user pass a "chain" of `Imputors` like `Interpolate, LOCF, NOC`?

**Comment by rofinn** [comment]
The general ideas was that you can compose imputors with function composition:

```
Model(
    0.3,
    Impute.interp!(; context=ctx) ∘ Impute.locf!() ∘ Impute.nocb!()
)
```

I suppose one way to support this would be to return a Chain imputor, but I'd like to minimize the number of imputor types that aren't actively doing something.
