### ISSUE TITLE
Use `skipmissing` instead of `drop` in `fill`?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/Impute.jl#50]

**Comment by rofinn** [comment]
`skipmissing` wouldn't work if we change the missingness function (e.g., `isnan`, `x -> x == 999999`).

**Comment by nickrobinson251** [comment]
ah, i didn't realise it was a goal of the package to impute non-`missing` values. If that's not documented, perhaps it'd be worth adding somewhere? 

Feel free to close this :)

**Comment by rofinn** [comment]
It's only really documented for the Context type and isn't currently used in any examples. I'll leave this open till that's added. If we move in the direction of having an `Impute.Iterators` module then the behaviour of `Impute.Iterators.drop` and `skipmissing` should become almost identical in the base case. Might be a good thing to test against though :)

**Comment by nickrobinson251** [comment]
> skipmissing wouldn't work if we change the missingness function

The more I think about this, the less I like.

Julia gives us `missing`, which is a monumentally useful thing, and I think it is reasonable to build for that case. If users need to `replace(X, 999999 => missing)` then they can do that before imputing

**Comment by rofinn** [comment]
Agreed. That’s why I’d like to move the current behaviour to an iterators module and default to using a multipass approach with an Impute.Dataset type.

**Comment by rofinn** [comment]
NOTE: most of these design decisions were made when Missing and Nullable we’re both things

**Comment by rofinn** [comment]
That's exactly what's happing in the new `Impute.substitute` call introduced in #69 

https://github.com/invenia/Impute.jl/blob/master/src/imputors/substitute.jl#L51
