### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by appleparan** [invenia/Impute.jl#56]
Tables got new version (v1.0.1) a weeks ago, however `Impute.jl` allow version up to 0.2.x.  Is there an issue with new `Tables.jl`? Because I'm not familiar with `Tables.jl` I'm not sure it is okay to bump versions in `Project.toml`.

**Comment by rofinn** [comment]
I don't believe the public API changes were breaking, so I think it's probably safe to bump the version to just "1" if the tests pass. I'd like to merge https://github.com/invenia/Impute.jl/pull/47/files before making too many updates though as I believe that standardizes some tests for all imputors.

**Comment by rofinn** [comment]
Looks like there are some breaking changes in updating to Tables 1.0. Specifically, some functionality has moved to TableOperations.jl and `TableOperations.select` is actively broken for row tables. I'll try and get a bug fixes released before updating.

**Comment by rofinn** [comment]
https://github.com/JuliaData/TableOperations.jl/pull/5
