### ISSUE TITLE
Consider renaming `Standardize`

### ISSUE THREAD

**Issue by rofinn** [invenia/Impute.jl#76]
Naming things is hard. Standardize, normalize, canonicalize are all really generic terms, so maybe we can think of an appropriate name specific to `missing`s?

https://github.com/invenia/Impute.jl/pull/69#discussion_r502623561

**Comment by nickrobinson251** [comment]
possible options with `missing` in the name:
- `Missingify`
- `MakeMissing`, `UseMissing`, `AsMissing`, `ToMissing`, `SpecifyMissing`, `DeclareMissing` 
- `MissingValue` / `MissingValues`

**Comment by nickrobinson251** [comment]
puns on making things "go missing":
- `Erase`, `Hide`, `Remove`, `Clean`, `Cleanse`, `Mask`
- `Refine`, `Rarefy`

**Comment by nickrobinson251** [comment]
> Naming things is hard.

**Comment by nickrobinson251** [comment]
`MissingValues((NaN, -9999.0, 0.0))` and `DeclareMissing((NaN, -9999.0, 0.0))` both seem better to me

**Comment by rofinn** [comment]
I'd like a short function name though :)
