### ISSUE TITLE
Solve conflict between DataFrames and DataTables

### ISSUE THREAD

**Issue by eperim** [invenia/Impute.jl#9]
Cloning this package, I get the following error:
```
INFO: Cloning Impute from https://github.com/invenia/Impute.jl.git
INFO: Computing changes...
ERROR: LoadError: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package DataFrames.
  However, this only means that package DataFrames is involved in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.
```
which is apparently related to a conflict between DataFrames and DataTables and keeps the package from being installed.

**Comment by rofinn** [comment]
Would you mind checking to see if the issue still existing on the latest master ([8ba51fe9](https://github.com/invenia/Impute.jl/commit/8ba51fe90b9c6b0184f8e9c29ef530f69c4c145e))?

**Comment by eperim** [comment]
Seems to be working perfectly now, thanks!
